// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/08/2026, 16:57:10
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/plugins/**/*.{js,ts,mjs}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/composables/**/*.{js,ts,mjs}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/utils/**/*.{js,ts,mjs}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivanv/.gemini/antigravity-ide/scratch/taurun-quote-produtos/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;